import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/providers/supabase_provider.dart';
import '../../../../core/utils/phone_formatter.dart';
import '../../data/datasources/auth_remote_datasource.dart';
import '../../data/repositories/auth_repository_impl.dart';
import '../../domain/usecases/request_otp_usecase.dart';
import '../../domain/usecases/verify_otp_usecase.dart';
import '../../domain/usecases/logout_usecase.dart';
import '../../../technician_profile/domain/entities/profile_entity.dart';
import '../../../technician_profile/presentation/providers/profile_provider.dart';

final authRemoteDatasourceProvider = Provider<AuthRemoteDatasource>((ref) {
  return AuthRemoteDatasource(ref.watch(supabaseClientProvider));
});

final authRepositoryProvider = Provider<AuthRepositoryImpl>((ref) {
  return AuthRepositoryImpl(ref.watch(authRemoteDatasourceProvider));
});

final requestOtpUsecaseProvider = Provider<RequestOtpUsecase>((ref) {
  return RequestOtpUsecase(ref.watch(authRepositoryProvider));
});

final verifyOtpUsecaseProvider = Provider<VerifyOtpUsecase>((ref) {
  return VerifyOtpUsecase(ref.watch(authRepositoryProvider));
});

final logoutUsecaseProvider = Provider<LogoutUsecase>((ref) {
  return LogoutUsecase(ref.watch(authRepositoryProvider));
});

class AuthUiState {
  final bool isLoading;
  final String? errorMessage;
  final String? phoneNumber;
  final bool otpSent;

  const AuthUiState({
    this.isLoading = false,
    this.errorMessage,
    this.phoneNumber,
    this.otpSent = false,
  });

  AuthUiState copyWith({
    bool? isLoading,
    String? errorMessage,
    String? phoneNumber,
    bool? otpSent,
    bool clearError = false,
  }) {
    return AuthUiState(
      isLoading: isLoading ?? this.isLoading,
      errorMessage: clearError ? null : (errorMessage ?? this.errorMessage),
      phoneNumber: phoneNumber ?? this.phoneNumber,
      otpSent: otpSent ?? this.otpSent,
    );
  }
}

class AuthNotifier extends StateNotifier<AuthUiState> {
  final RequestOtpUsecase _requestOtp;
  final VerifyOtpUsecase _verifyOtp;
  final LogoutUsecase _logout;
  final Ref _ref;

  AuthNotifier(this._requestOtp, this._verifyOtp, this._logout, this._ref)
      : super(const AuthUiState());

  Future<bool> completeOnboarding({
    required String name,
    required List<ServiceType> services,
  }) async {
    state = state.copyWith(isLoading: true, clearError: true);
    try {
      final supabase = _ref.read(supabaseClientProvider);
      final authUser = supabase.auth.currentUser;
      if (authUser == null) throw Exception('No session found');

      // 1. Create User (Slug is auto-generated by DB trigger)
      final datasource = _ref.read(authRemoteDatasourceProvider);
      await datasource.createUser(
        authId: authUser.id,
        fullName: name,
        phoneNumber: authUser.phone ?? '',
      );

      // 2. Create Profile
      final profileRepo = _ref.read(profileRepositoryProvider);
      final now = DateTime.now();
      
      // Slug used in URL will match the one generated by DB
      final tempSlug = name.trim().toLowerCase().replaceAll(' ', '-');
      
      final profile = ProfileEntity(
        id: '',
        userId: authUser.id,
        displayName: name,
        services: services,
        whatsappNumber: authUser.phone ?? '',
        isPublic: true,
        profileUrl: 'keystone.app/p/$tempSlug',
        createdAt: now,
        updatedAt: now,
      );
      
      await profileRepo.createProfile(profile);
      state = state.copyWith(isLoading: false);
      return true;
    } catch (e) {
      state = state.copyWith(isLoading: false, errorMessage: e.toString());
      return false;
    }
  }

  Future<bool> requestOtp(String phoneNumber) async {
    state = state.copyWith(isLoading: true, clearError: true);
    try {
      await _requestOtp(RequestOtpParams(phoneNumber: phoneNumber));
      state = state.copyWith(
        isLoading: false,
        phoneNumber: PhoneFormatter.normalize(phoneNumber),
        otpSent: true,
      );
      return true;
    } catch (e) {
      state = state.copyWith(isLoading: false, errorMessage: e.toString());
      return false;
    }
  }

  Future<bool> verifyOtp(String token) async {
    if (state.phoneNumber == null) return false;
    state = state.copyWith(isLoading: true, clearError: true);
    try {
      await _verifyOtp(VerifyOtpParams(
        phoneNumber: state.phoneNumber!,
        token: token,
      ));
      state = state.copyWith(isLoading: false);
      return true;
    } catch (e) {
      state = state.copyWith(isLoading: false, errorMessage: e.toString());
      return false;
    }
  }

  Future<void> logout() async {
    await _logout();
    state = const AuthUiState();
  }
}

final authNotifierProvider =
    StateNotifierProvider<AuthNotifier, AuthUiState>((ref) {
  return AuthNotifier(
    ref.watch(requestOtpUsecaseProvider),
    ref.watch(verifyOtpUsecaseProvider),
    ref.watch(logoutUsecaseProvider),
    ref,
  );
});
