name: keystone
description: Job management for professional locksmiths in Ghana
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Backend
  supabase_flutter: ^2.5.0

  # Local storage (offline-first)
  hive_flutter: ^1.1.0

  # Navigation
  go_router: ^13.2.0

  # OTP input
  pinput: ^3.0.1

  # Image handling
  image_picker: ^1.1.2
  flutter_image_compress: ^2.2.0

  # Utilities
  url_launcher: ^6.2.6
  share_plus: ^9.0.0
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  uuid: ^4.4.0
  google_fonts: ^6.2.1

  # Immutable models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/fonts/
  fonts:
    - family: BarlowSemiCondensed
      fonts:
        - asset: assets/fonts/BarlowSemiCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/BarlowSemiCondensed-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/BarlowSemiCondensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/BarlowSemiCondensed-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/BarlowSemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/BarlowSemiCondensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/BarlowSemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/BarlowSemiCondensed-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/BarlowSemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/BarlowSemiCondensed-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/BarlowSemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BarlowSemiCondensed-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/BarlowSemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/BarlowSemiCondensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/BarlowSemiCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/BarlowSemiCondensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/BarlowSemiCondensed-Black.ttf
          weight: 900
        - asset: assets/fonts/BarlowSemiCondensed-BlackItalic.ttf
          weight: 900
          style: italic

